<a href="https://colab.research.google.com/github/GusXKern/BikeShareCaseStudy/blob/main/Bike_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [3]:
q2_2019 = pd.read_csv("/content/Divvy_Trips_2019_Q2.csv")
q3_2019 = pd.read_csv("/content/Divvy_Trips_2019_Q3.csv")
q4_2019 = pd.read_csv("/content/Divvy_Trips_2019_Q4.csv")
q1_2020 = pd.read_csv("/content/Divvy_Trips_2020_Q1.csv")

In [4]:
print("\nQ2 2019 Data Info:")
q2_2019.info()
print("\nQ3 2019 Data Info:")
q3_2019.info()
print("\nQ4 2020 Data Info:")
q4_2019.info()
print("\nQ1 2020 Data Info:")
q1_2020.info()

Q2 2019 Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 12 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   trip_id            1048575 non-null  int64
 1   start_time         1048575 non-null  object
 2   end_time           1048575 non-null  object
 3   bikeid             1048575 non-null  int64
 4   tripduration       1048575 non-null  object
 5   from_station_id    1048575 non-null  int64
 6   from_station_name  1048575 non-null  object
 7   to_station_id      1048575 non-null  int64
 8   to_station_name    1048575 non-null  object
 9   usertype           1048575 non-null  object
 10  gender             879106 non-null   object
 11  birthyear          883467 non-null   float64
dtypes: float64(1), int64(4), object(7)
memory usage: 96.0+ MB

Q3 2019 Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1640718 entries, 0 to 1640717
Data columns (total 12 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   trip_id            1640718 non-null  int64
 1   start_time         1640718 non-null  object
 2   end_time           1640718 non-null  object
 3   bikeid             1640718 non-null  int64
 4   tripduration       1640718 non-null  object
 5   from_station_id    1640718 non-null  int64
 6   from_station_name  1640718 non-null  object
 7   to_station_id      1640718 non-null  int64
 8   to_station_name    1640718 non-null  object
 9   usertype           1640718 non-null  object
 10  gender             1353368 non-null  object
 11  birthyear          1362624 non-null  float64
dtypes: float64(1), int64(4), object(7)
memory usage: 150.2+ MB

Q4 2020 Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 704054 entries, 0 to 704053
Data columns (total 12 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   trip_id            704054 non-null  int64
 1   start_time         704054 non-null  object
 2   end_time           704054 non-null  object
 3   bikeid             704054 non-null  int64
 4   tripduration       704054 non-null  object
 5   from_station_id    704054 non-null  int64
 6   from_station_name  704054 non-null  object
 7   to_station_id      704054 non-null  int64
 8   to_station_name    704054 non-null  object
 9   usertype           704054 non-null  object
 10  gender             637463 non-null  object
 11  birthyear          642373 non-null  float64
dtypes: float64(1), int64(4), object(7)
memory usage: 64.5+ MB

Q1 2020 Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 426887 entries, 0 to 426886
Data columns (total 13 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   trip_id            426887 non-null  object
 1   bikeid             426887 non-null  object
 2   start_time         426887 non-null  object
 3   end_time           426887 non-null  object
 4   from_station_name  426887 non-null  object
 5   from_station_id    426887 non-null  int64
 6   to_station_name    426886 non-null  object
 7   to_station_id      426886 non-null  float64
 8   start_lat          426887 non-null  float64
 9   start_lng          426887 non-null  float64
 10  end_lat            426886 non-null  float64
 11  end_lng            426886 non-null  float64
 12  usertype           426887 non-null  object
dtypes: float64(5), int64(1), object(7)
memory usage: 42.3+ MB

In [5]:
all_2019_trips = pd.concat([q2_2019, q3_2019,q4_2019], ignore_index=True)


all_2019_trips['trip_id'] = all_2019_trips['trip_id'].astype(str)
all_2019_trips['bikeid'] = all_2019_trips['bikeid'].astype(str)

print(all_2019_trips.head(10))

    trip_id     start_time       end_time bikeid tripduration  \
0  22178529  4/1/2019 0:02  4/1/2019 0:09   6251          446
1  22178530  4/1/2019 0:03  4/1/2019 0:20   6226     1,048.00
2  22178531  4/1/2019 0:11  4/1/2019 0:15   5649          252
3  22178532  4/1/2019 0:13  4/1/2019 0:18   4151          357
4  22178533  4/1/2019 0:19  4/1/2019 0:36   3270     1,007.00
5  22178534  4/1/2019 0:19  4/1/2019 0:23   3123          257
6  22178535  4/1/2019 0:26  4/1/2019 0:35   6418          548
7  22178536  4/1/2019 0:29  4/1/2019 0:36   4513          383
8  22178537  4/1/2019 0:32  4/1/2019 1:07   3280     2,137.00
9  22178538  4/1/2019 0:32  4/1/2019 1:07   5534     2,120.00

   from_station_id           from_station_name  to_station_id  \
0               81          Daley Center Plaza             56
1              317         Wood St & Taylor St             59
2              283   LaSalle St & Jackson Blvd            174
3               26    McClurg Ct & Illinois St            133
4              202        Halsted St & 18th St            129
5              420         Ellis Ave & 55th St            426
6              503   Drake Ave & Fullerton Ave            500
7              260  Kedzie Ave & Milwaukee Ave            499
8              211      St. Clair St & Erie St            211
9              211      St. Clair St & Erie St            211

                   to_station_name    usertype  gender  birthyear
0        Desplaines St & Kinzie St  Subscriber    Male     1975.0
1        Wabash Ave & Roosevelt Rd  Subscriber  Female     1984.0
2            Canal St & Madison St  Subscriber    Male     1990.0
3         Kingsbury St & Kinzie St  Subscriber    Male     1993.0
4        Blue Island Ave & 18th St  Subscriber    Male     1992.0
5              Ellis Ave & 60th St  Subscriber    Male     1999.0
6  Central Park Ave & Elbridge Ave  Subscriber    Male     1969.0
7                  Kosciuszko Park  Subscriber    Male     1991.0
8           St. Clair St & Erie St    Customer     NaN        NaN
9           St. Clair St & Erie St    Customer     NaN        NaN

In [6]:
q1_2020_test = q1_2020.drop(columns=['start_lat', 'start_lng', 'end_lat', 'end_lng', 'birthyear', 'gender',
'tripduration'], errors='ignore')
q1_2020_test.head(10)

,trip_id,bikeid,start_time,end_time,from_station_name,from_station_id,to_station_name,to_station_id,usertype
0,EACB19130B0CDA4A,docked_bike,1/21/2020 20:06,1/21/2020 20:14,Western Ave & Leland Ave,239,Clark St & Leland Ave,326.0,member
1,8FED874C809DC021,docked_bike,1/30/2020 14:22,1/30/2020 14:26,Clark St & Montrose Ave,234,Southport Ave & Irving Park Rd,318.0,member
2,789F3C21E472CA96,docked_bike,1/9/2020 19:29,1/9/2020 19:32,Broadway & Belmont Ave,296,Wilton Ave & Belmont Ave,117.0,member
3,C9A388DAC6ABF313,docked_bike,1/6/2020 16:17,1/6/2020 16:25,Clark St & Randolph St,51,Fairbanks Ct & Grand Ave,24.0,member
4,943BC3CBECCFD662,docked_bike,1/30/2020 8:37,1/30/2020 8:42,Clinton St & Lake St,66,Wells St & Hubbard St,212.0,member
5,6D9C8A6938165C11,docked_bike,1/10/2020 12:33,1/10/2020 12:37,Wells St & Hubbard St,212,Desplaines St & Randolph St,96.0,member
6,31EB9B8F406D4C82,docked_bike,1/10/2020 13:07,1/10/2020 13:12,Desplaines St & Randolph St,96,Wells St & Hubbard St,212.0,member
7,A2B24E3F9C9720E3,docked_bike,1/10/2020 7:24,1/10/2020 7:29,Desplaines St & Randolph St,96,Wells St & Hubbard St,212.0,member
8,5E3F01E1441730B7,docked_bike,1/31/2020 16:37,1/31/2020 16:42,Wells St & Hubbard St,212,Desplaines St & Randolph St,96.0,member
9,19DC57F7E3140131,docked_bike,1/31/2020 9:39,1/31/2020 9:42,Clark St & Lake St,38,Orleans St & Merchandise Mart Plaza,100.0,member

In [7]:
print("Columns for combo 2019:\n", all_2019_trips.columns)
print("\nColumns for Q1 2020:\n", q1_2020_test.columns)

Columns for combo 2019:
 Index(['trip_id', 'start_time', 'end_time', 'bikeid', 'tripduration',
       'from_station_id', 'from_station_name', 'to_station_id',
       'to_station_name', 'usertype', 'gender', 'birthyear'],
      dtype='object')

Columns for Q1 2020:
 Index(['trip_id', 'bikeid', 'start_time', 'end_time', 'from_station_name',
       'from_station_id', 'to_station_name', 'to_station_id', 'usertype'],
      dtype='object')

In [8]:
print("\nCombined 2019 Data Info:")
all_2019_trips.info()
print("\nQ1 2020 Data Info:")
q1_2020.info()

Combined 2019 Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3393347 entries, 0 to 3393346
Data columns (total 12 columns):
 #   Column             Dtype
---  ------             -----
 0   trip_id            object
 1   start_time         object
 2   end_time           object
 3   bikeid             object
 4   tripduration       object
 5   from_station_id    int64
 6   from_station_name  object
 7   to_station_id      int64
 8   to_station_name    object
 9   usertype           object
 10  gender             object
 11  birthyear          float64
dtypes: float64(1), int64(2), object(9)
memory usage: 310.7+ MB

Q1 2020 Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 426887 entries, 0 to 426886
Data columns (total 13 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   trip_id            426887 non-null  object
 1   bikeid             426887 non-null  object
 2   start_time         426887 non-null  object
 3   end_time           426887 non-null  object
 4   from_station_name  426887 non-null  object
 5   from_station_id    426887 non-null  int64
 6   to_station_name    426886 non-null  object
 7   to_station_id      426886 non-null  float64
 8   start_lat          426887 non-null  float64
 9   start_lng          426887 non-null  float64
 10  end_lat            426886 non-null  float64
 11  end_lng            426886 non-null  float64
 12  usertype           426887 non-null  object
dtypes: float64(5), int64(1), object(7)
memory usage: 42.3+ MB

In [9]:
all_trips = pd.concat([all_2019_trips,q1_2020_test], ignore_index=True)
all_trips.sort_values(by='start_time').head(10)

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,gender,birthyear
3492626,1068AB1B8F12FE23,1/1/2020 0:04,1/1/2020 0:17,docked_bike,NaN,115,Sheffield Ave & Wellington Ave,246.0,Ashland Ave & Belle Plaine Ave,casual,NaN,NaN
3537123,DCF74A0EB3284B3E,1/1/2020 0:10,1/1/2020 0:10,docked_bike,NaN,81,Daley Center Plaza,81.0,Daley Center Plaza,member,NaN,NaN
3433158,1C78B5F337CBFC93,1/1/2020 0:11,1/1/2020 0:13,docked_bike,NaN,240,Sheridan Rd & Irving Park Rd,256.0,Broadway & Sheridan Rd,member,NaN,NaN
3537124,4DE50A4FC7687A0D,1/1/2020 0:11,1/1/2020 0:15,docked_bike,NaN,81,Daley Center Plaza,624.0,Dearborn St & Van Buren St,member,NaN,NaN
3487815,D231CE7990A3AA52,1/1/2020 0:12,1/1/2020 0:14,docked_bike,NaN,626,Delano Ct & Roosevelt Rd,59.0,Wabash Ave & Roosevelt Rd,member,NaN,NaN
3402762,2295556346560999,1/1/2020 0:19,1/1/2020 0:26,docked_bike,NaN,326,Clark St & Leland Ave,318.0,Southport Ave & Irving Park Rd,member,NaN,NaN
3398710,EB21BB139ABF6174,1/1/2020 0:21,1/1/2020 0:29,docked_bike,NaN,326,Clark St & Leland Ave,460.0,Clark St & Bryn Mawr Ave,member,NaN,NaN
3487380,E0ECDAD877BC9A09,1/1/2020 0:21,1/1/2020 0:29,docked_bike,NaN,326,Clark St & Leland Ave,460.0,Clark St & Bryn Mawr Ave,member,NaN,NaN
3446019,5C336EDA9744D287,1/1/2020 0:22,1/1/2020 0:32,docked_bike,NaN,347,Ashland Ave & Grace St,153.0,Southport Ave & Wellington Ave,casual,NaN,NaN
3466560,1A41E3B460E4BFCF,1/1/2020 0:23,1/1/2020 0:33,docked_bike,NaN,3,Shedd Aquarium,41.0,Federal St & Polk St,member,NaN,NaN

In [10]:
# Inspect the new table that has been created
print("\nList of column names:\n", all_trips.columns)
print("\nHow many rows are in data frame?", len(all_trips))
print("\nDimensions of the data frame:", all_trips.shape)
print("\nSee the first 6 rows of data frame:\n", all_trips.head())
print("\nSee list of columns and data types:\n")
all_trips.info()
# Statistical summary of data (mainly for numerics)
print("\nStatistical summary of data:\n", all_trips.describe())

List of column names:
 Index(['trip_id', 'start_time', 'end_time', 'bikeid', 'tripduration',
       'from_station_id', 'from_station_name', 'to_station_id',
       'to_station_name', 'usertype', 'gender', 'birthyear'],
      dtype='object')

How many rows are in data frame? 3820234

Dimensions of the data frame: (3820234, 12)

See the first 6 rows of data frame:
     trip_id     start_time       end_time bikeid tripduration  \
0  22178529  4/1/2019 0:02  4/1/2019 0:09   6251          446
1  22178530  4/1/2019 0:03  4/1/2019 0:20   6226     1,048.00
2  22178531  4/1/2019 0:11  4/1/2019 0:15   5649          252
3  22178532  4/1/2019 0:13  4/1/2019 0:18   4151          357
4  22178533  4/1/2019 0:19  4/1/2019 0:36   3270     1,007.00

   from_station_id          from_station_name  to_station_id  \
0               81         Daley Center Plaza           56.0
1              317        Wood St & Taylor St           59.0
2              283  LaSalle St & Jackson Blvd          174.0
3               26   McClurg Ct & Illinois St          133.0
4              202       Halsted St & 18th St          129.0

             to_station_name    usertype  gender  birthyear
0  Desplaines St & Kinzie St  Subscriber    Male     1975.0
1  Wabash Ave & Roosevelt Rd  Subscriber  Female     1984.0
2      Canal St & Madison St  Subscriber    Male     1990.0
3   Kingsbury St & Kinzie St  Subscriber    Male     1993.0
4  Blue Island Ave & 18th St  Subscriber    Male     1992.0

See list of columns and data types:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3820234 entries, 0 to 3820233
Data columns (total 12 columns):
 #   Column             Dtype
---  ------             -----
 0   trip_id            object
 1   start_time         object
 2   end_time           object
 3   bikeid             object
 4   tripduration       object
 5   from_station_id    int64
 6   from_station_name  object
 7   to_station_id      float64
 8   to_station_name    object
 9   usertype           object
 10  gender             object
 11  birthyear          float64
dtypes: float64(2), int64(1), object(9)
memory usage: 349.8+ MB

Statistical summary of data:
        from_station_id  to_station_id     birthyear
count     3.820234e+06   3.820233e+06  2.888464e+06
mean      2.029117e+02   2.037422e+02  1.984339e+03
std       1.571851e+02   1.572368e+02  1.079517e+01
min       1.000000e+00   1.000000e+00  1.759000e+03
25%       7.700000e+01   7.700000e+01  1.980000e+03
50%       1.740000e+02   1.740000e+02  1.988000e+03
75%       2.900000e+02   2.910000e+02  1.992000e+03
max       6.750000e+02   6.750000e+02  2.014000e+03

In [11]:
all_trips['usertype'].value_counts()

usertype
Subscriber    2559525
Customer       833822
member         378407
casual          48480
Name: count, dtype: int64

In [12]:
all_trips['usertype'] = all_trips['usertype'].replace({
'Subscriber': 'member',
'Customer': 'casual'
})

In [13]:
all_trips['usertype'].value_counts()

usertype
member    2937932
casual     882302
Name: count, dtype: int64

In [14]:
# Convert both columns using 'mixed' format to handle different styles
all_trips['start_time'] = pd.to_datetime(all_trips['start_time'], format='mixed')
all_trips['end_time'] = pd.to_datetime(all_trips['end_time'], format='mixed')

# Double check the results
print(all_trips[['start_time', 'end_time']].head())

           start_time            end_time
0 2019-04-01 00:02:00 2019-04-01 00:09:00
1 2019-04-01 00:03:00 2019-04-01 00:20:00
2 2019-04-01 00:11:00 2019-04-01 00:15:00
3 2019-04-01 00:13:00 2019-04-01 00:18:00
4 2019-04-01 00:19:00 2019-04-01 00:36:00

In [15]:
#Code to use start/end time to make date, month, day, year, day of the week columns
all_trips['date'] = all_trips['start_time'].dt.date
all_trips['month'] = all_trips['start_time'].dt.month
all_trips['day'] = all_trips['start_time'].dt.day
all_trips['year'] = all_trips['start_time'].dt.year
all_trips['day_of_week'] = all_trips['start_time'].dt.day_name()

In [16]:
#Code to make ride_length column
all_trips['ride_length'] = (all_trips['end_time']-all_trips['start_time']).dt.total_seconds()
print("\nData types after adding date columns and ride_length:\n")
all_trips.info()

Data types after adding date columns and ride_length:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3820234 entries, 0 to 3820233
Data columns (total 18 columns):
 #   Column             Dtype
---  ------             -----
 0   trip_id            object
 1   start_time         datetime64[ns]
 2   end_time           datetime64[ns]
 3   bikeid             object
 4   tripduration       object
 5   from_station_id    int64
 6   from_station_name  object
 7   to_station_id      float64
 8   to_station_name    object
 9   usertype           object
 10  gender             object
 11  birthyear          float64
 12  date               object
 13  month              int32
 14  day                int32
 15  year               int32
 16  day_of_week        object
 17  ride_length        float64
dtypes: datetime64[ns](2), float64(3), int32(3), int64(1), object(9)
memory usage: 480.9+ MB

In [17]:
#Using Boolean Masking to see how many negative values there are
all_trips['ride_length'].sort_values(ignore_index=True)

neg_ride = all_trips['ride_length'] < 0

len(all_trips[neg_ride])

38

In [18]:
# Code to make a copy of the dataset with any rows with negative trip durations values excluded
all_trips_v2 = all_trips[(all_trips['from_station_name'] != "HQ QR") & (all_trips['ride_length'] >=
0)].copy()

In [19]:
# Descriptive analysis on ride_length (all figures in seconds)
print("\nDescriptive statistics for ride_length:\n", all_trips_v2['ride_length'].describe())

Descriptive statistics for ride_length:
 count    3.816454e+06
mean     1.476782e+03
std      3.115797e+04
min      0.000000e+00
25%      4.200000e+02
50%      7.200000e+02
75%      1.278000e+03
max      9.387000e+06
Name: ride_length, dtype: float64

In [20]:
# Compare members and casual users
print("\nRide length statistics grouped by member_casual:\n",
all_trips_v2.groupby('usertype')['ride_length'].agg(['mean', 'median', 'max', 'min']))

Ride length statistics grouped by member_casual:
                  mean  median        max  min
usertype
casual    3575.306388  1549.0  9387000.0  0.0
member     849.258226   600.0  9056634.0  0.0

In [21]:
# See the average ride time by each day for members vs casual users
print("\nAverage ride length by member type and day of the week:\n",
all_trips_v2.groupby(['usertype', 'day_of_week'])['ride_length'].mean())

Average ride length by member type and day of the week:
 usertype  day_of_week
casual    Friday         3822.845312
          Monday         3372.307418
          Saturday       3362.583553
          Sunday         3607.810028
          Thursday       3705.995669
          Tuesday        3596.363496
          Wednesday      3718.762116
member    Friday          824.384703
          Monday          842.556210
          Saturday        968.099132
          Sunday          919.015264
          Thursday        822.847034
          Tuesday         826.152760
          Wednesday       823.974769
Name: ride_length, dtype: float64

In [22]:
# The days of the week need to be ordered for correct sorting for analysis
days_order = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]
all_trips_v2['day_of_week'] = pd.Categorical(all_trips_v2['day_of_week'],
categories=days_order, ordered=True)

In [23]:
# Now, run the aggregation again to see the sorted result
print("\nAverage ride length (sorted by day of week):\n", all_trips_v2.groupby(['usertype',
'day_of_week'])['ride_length'].mean())

/tmp/ipykernel_227/3711734380.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print("\nAverage ride length (sorted by day of week):\n", all_trips_v2.groupby(['usertype',

Average ride length (sorted by day of week):
 usertype  day_of_week
casual    Sunday         3607.810028
          Monday         3372.307418
          Tuesday        3596.363496
          Wednesday      3718.762116
          Thursday       3705.995669
          Friday         3822.845312
          Saturday       3362.583553
member    Sunday          919.015264
          Monday          842.556210
          Tuesday         826.152760
          Wednesday       823.974769
          Thursday        822.847034
          Friday          824.384703
          Saturday        968.099132
Name: ride_length, dtype: float64

In [24]:
# Analyze ridership data by type and weekday
summary_stats = all_trips_v2.groupby(['usertype', 'day_of_week']).agg(
number_of_rides=('trip_id', 'count'),
average_duration=('ride_length', 'mean')
).reset_index()

/tmp/ipykernel_227/2424166265.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  summary_stats = all_trips_v2.groupby(['usertype', 'day_of_week']).agg(

In [25]:
print("\nSummary of rides and duration by rider type and weekday:\n", summary_stats)

Summary of rides and duration by rider type and weekday:
    usertype day_of_week  number_of_rides  average_duration
0    casual      Sunday           174768       3607.810028
1    casual      Monday           103296       3372.307418
2    casual     Tuesday            90510       3596.363496
3    casual   Wednesday            92457       3718.762116
4    casual    Thursday           101142       3705.995669
5    casual      Friday           117753       3822.845312
6    casual    Saturday           198604       3362.583553
7    member      Sunday           260608        919.015264
8    member      Monday           472196        842.556210
9    member     Tuesday           508445        826.152760
10   member   Wednesday           500329        823.974769
11   member    Thursday           479341        822.847034
12   member      Friday           439526        824.384703
13   member    Saturday           277479        968.099132

In [55]:
counts_2 = all_trips_v2.groupby(['usertype', 'month']).agg(
number_of_rides=('trip_id', 'count'),
average_duration=('ride_length', 'mean')
)

print(counts_2)
# Reset the index so 'usertype' and 'month' become regular columns
counts_2_final = counts_2.reset_index()

# Now export the new version
counts_2_final.to_csv('avg_ride_length_month_2.csv', index=False)

from google.colab import files
files.download('avg_ride_length_month_2.csv')

                number_of_rides  average_duration
usertype month
casual   1                 7785       9698.990366
         2                12314       7997.141465
         3                24615       4250.115783
         4                47744       3056.550352
         5                81624       3074.420024
         6               106566       2764.076347
         7               175632       3587.029499
         8               186889       4020.451343
         9               129173       3100.002183
         10               71035       3539.529021
         11               18723       4021.965817
         12               16430       3799.959404
member   1               136099        668.846208
         2               126714        768.283536
         3               115593        859.981833
         4               217566        810.811616
         5               285834        831.030248
         6               309241        867.873018
         7               381683        985.999982
         8               403295        971.132429
         9               364046        847.838916
         10              300751        781.853251
         11              158440        745.924255
         12              138662        684.909838

In [56]:
counts_3 = all_trips_v2.groupby(['usertype', 'day_of_week']).agg(
number_of_rides=('trip_id', 'count'),
average_duration=('ride_length', 'mean')
)

print(counts_3)
# Reset the index so 'usertype' and 'month' become regular columns
counts_3_final = counts_3.reset_index()

# Now export the new version
counts_3_final.to_csv('avg_ride_length_2.csv', index=False)

from google.colab import files
files.download('avg_ride_length_2.csv')

/tmp/ipykernel_227/708466349.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  counts_3 = all_trips_v2.groupby(['usertype', 'day_of_week']).agg(

                      number_of_rides  average_duration
usertype day_of_week
casual   Sunday                174768       3607.810028
         Monday                103296       3372.307418
         Tuesday                90510       3596.363496
         Wednesday              92457       3718.762116
         Thursday              101142       3705.995669
         Friday                117753       3822.845312
         Saturday              198604       3362.583553
member   Sunday                260608        919.015264
         Monday                472196        842.556210
         Tuesday               508445        826.152760
         Wednesday             500329        823.974769
         Thursday              479341        822.847034
         Friday                439526        824.384703
         Saturday              277479        968.099132

In [27]:
# Saving user/day of week by ride len for use in Tableau
counts = all_trips_v2.groupby(['usertype',
'day_of_week'])['ride_length'].mean().reset_index()
counts.to_csv('avg_ride_length.csv', index=False)

/tmp/ipykernel_227/2743300987.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  counts = all_trips_v2.groupby(['usertype',

In [28]:
counts = all_trips_v2.groupby(['usertype',
'month'])['ride_length'].mean().reset_index()
counts.to_csv('avg_ride_length_month.csv', index=False)

In [29]:
counts.to_csv('avg_ride_length_month.csv', index=False)

In [30]:
from google.colab import files
files.download('avg_ride_length_month.csv')

In [47]:
print(q1_2020.info())
print(all_trips_v2.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 426887 entries, 0 to 426886
Data columns (total 13 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   trip_id            426887 non-null  object
 1   bikeid             426887 non-null  object
 2   start_time         426887 non-null  object
 3   end_time           426887 non-null  object
 4   from_station_name  426887 non-null  object
 5   from_station_id    426887 non-null  int64
 6   to_station_name    426886 non-null  object
 7   to_station_id      426886 non-null  float64
 8   start_lat          426887 non-null  float64
 9   start_lng          426887 non-null  float64
 10  end_lat            426886 non-null  float64
 11  end_lng            426886 non-null  float64
 12  usertype           426887 non-null  object
dtypes: float64(5), int64(1), object(7)
memory usage: 42.3+ MB
None
<class 'pandas.core.frame.DataFrame'>
Index: 3816454 entries, 0 to 3820233
Data columns (total 18 columns):
 #   Column             Dtype
---  ------             -----
 0   trip_id            object
 1   start_time         datetime64[ns]
 2   end_time           datetime64[ns]
 3   bikeid             object
 4   tripduration       object
 5   from_station_id    int64
 6   from_station_name  object
 7   to_station_id      float64
 8   to_station_name    object
 9   usertype           object
 10  gender             object
 11  birthyear          float64
 12  date               object
 13  month              int32
 14  day                int32
 15  year               int32
 16  day_of_week        category
 17  ride_length        float64
dtypes: category(1), datetime64[ns](2), float64(3), int32(3), int64(1), object(8)
memory usage: 484.1+ MB
None

In [48]:
# 1. Create the lookup table from your 2020 file
station_lookup = q1_2020[['to_station_id', 'end_lat', 'end_lng']].drop_duplicates(subset=['to_station_id'])

# 2. Add 'to_station_id' to the groupby so it's preserved
grouped = all_trips_v2.groupby(['usertype', 'to_station_name', 'to_station_id']).agg(
    number_of_rides=('trip_id', 'count')
)

# 3. Get top 5 and use reset_index() to make 'to_station_id' a column again
top_5_per_user = grouped.sort_values(['usertype', 'number_of_rides'], ascending=[True, False]) \
                        .groupby('usertype') \
                        .head(5) \
                        .reset_index()  # <--- THIS IS THE KEY FIX

# 4. Now the merge will work because 'to_station_id' exists as a column
top_5_mapped = top_5_per_user.merge(station_lookup,
                                    on='to_station_id',
                                    how='left')

print(top_5_mapped)

  usertype               to_station_name  to_station_id  number_of_rides  \
0   casual       Streeter Dr & Grand Ave           35.0            65641
1   casual     Lake Shore Dr & Monroe St           76.0            30311
2   casual               Millennium Park           90.0            24987
3   casual         Michigan Ave & Oak St           85.0            23231
4   casual    Lake Shore Dr & North Blvd          268.0            22672
5   member           Canal St & Adams St          192.0            48595
6   member  Clinton St & Washington Blvd           91.0            47343
7   member       Clinton St & Madison St           77.0            43969
8   member            Daley Center Plaza           81.0            30605
9   member      Kingsbury St & Kinzie St          133.0            30102

   end_lat  end_lng
0  41.8923 -87.6120
1  41.8810 -87.6167
2  41.8810 -87.6241
3  41.9010 -87.6238
4  41.9117 -87.6268
5  41.8793 -87.6399
6  41.8834 -87.6412
7  41.8822 -87.6411
8  41.8842 -87.6296
9  41.8892 -87.6385

In [49]:
top_5_mapped.to_csv('top_5_lat.csv', index=False)
from google.colab import files
files.download('top_5_lat.csv')